version: '3'
services:
  mongodb:
    image: mongo:4.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db
  dev_api:
    depends_on:
      - mongodb
    container_name: iotubig-backend
    links: 
      - mongodb
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    env_file:
      - .env.docker
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  mongodbdata: